name: Add Outside Sprint Tag

on:
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    env:
      TARGET: "proposal|progre"
      LABEL: "hanicaスプリント外"
    steps:
      - name: Set Variables
        id: set_variables
        run: |
          echo "target=$TARGET" >> $GITHUB_OUTPUT
          echo "label=$LABEL" >> $GITHUB_OUTPUT
      - name: Check PR title
        id: check_title
        run: echo "contains_string=$(echo ${{ github.event.pull_request.title }} | egrep -i -c -e $TARGET)"  >> $GITHUB_OUTPUT

      - name: Add label to PR
        if: steps.check_title.outputs.contains_string == '1'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            const response = await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [${{ steps.set_variables.outputs.label }}]
            });
            
            console.log('Label added to PR:', response);
