name: Add Outside Sprint Tag

on:
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    env:
      TARGET: 'proposal|progre'
      LABEL: 'hanicaスプリント外'
    steps:
      # 本当はcontainsで処理できるといいんだけど、複数条件を指定できないので、grepで処理している
      - name: Check PR title
        id: check_title
        run: echo "contains_string=$(echo ${{ github.event.pull_request.title }} | egrep -i -c '${{ env.TARGET }}')"  >> $GITHUB_OUTPUT

      - name: Add label to PR
        if: |
          steps.check_title.outputs.contains_string == '1' &&
          !contains(github.event.pull_request.labels.*.name, 'hanicaスプリント外')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            const response = await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ["${{ env.LABEL }}"]
            });
            
            console.log('Label added to PR:', response);

      - name: Remove label from PR
        if: |
          steps.check_title.outputs.contains_string == '0' &&
          contains(github.event.pull_request.labels.*.name, 'hanicaスプリント外')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            const response = await github.rest.issues.removeLabel({
              owner,
              repo,
              issue_number,
              labels: ["${{ env.LABEL }}"]
            });
            
            console.log('Label removed from PR:', response);
