name: Add Proposal Tag

on:
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        id: check_title
        run: echo "::set-output name=contains_string::$(echo ${{ github.event.pull_request.title }} | grep -c 'proposal')"

      - name: Add label to PR
        if: steps.check_title.outputs.contains_string == '1'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const label = 'proposal';
            
            const response = await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [label]
            });
            
            console.log('Label added to PR:', response);
